import { apiClient } from "./client";
export type NotificationResourceType = "repair" | "claim" | "return" | "support_ticket" | "guidance" | "procurement_request" | "procurement_quotation" | "service_request" | "service_quotation" | "maintenance_plan";
export interface CustomerNotification { id: string; type: string; title: string; safePreview: string; resourceType: NotificationResourceType; resourceId: string; readAt: string | null; createdAt: string; expiresAt: string | null; mandatory: boolean; }
export interface NotificationPreferences { version: string; mandatoryCategories: string[]; optionalCategories: Record<string, boolean>; channels: { inApp: boolean; email: false; sms: false; push: false }; }
const resources = new Set<NotificationResourceType>(["repair","claim","return","support_ticket","guidance","procurement_request","procurement_quotation","service_request","service_quotation","maintenance_plan"]);
const record = (value: unknown) => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Unexpected notification response"); return value as Record<string, unknown>; };
const text = (value: unknown, message: string) => { if (typeof value !== "string" || !value.trim()) throw new Error(message); return value; };
const array = (value: unknown) => Array.isArray(value) ? value : [];
const booleanRecord = (value: unknown): Record<string, boolean> => Object.fromEntries(Object.entries(record(value)).flatMap(([key, item]) => typeof item === "boolean" ? [[key, item]] : []));
const normalize = (value: unknown): CustomerNotification => { const item=record(value); const resourceType=text(item.resourceType,"Notification resource is unavailable") as NotificationResourceType; if(!resources.has(resourceType)) throw new Error("Notification resource is unavailable"); return { id:text(item.id ?? item._id,"Notification reference is unavailable"), type:text(item.type,"Notification type is unavailable"), title:text(item.title,"Notification title is unavailable"), safePreview:text(item.safePreview,"Notification preview is unavailable"), resourceType, resourceId:text(item.resourceId,"Notification resource is unavailable"), readAt:typeof item.readAt==="string"?item.readAt:null, createdAt:text(item.createdAt,"Notification date is unavailable"), expiresAt:typeof item.expiresAt==="string"?item.expiresAt:null, mandatory:item.mandatory===true }; };
export async function listNotifications(page=1) { const result=record(await apiClient.get<unknown>("/notifications?page="+encodeURIComponent(String(page)))); return { notifications:array(result.notifications).map(normalize), pagination:record(result.pagination) }; }
export async function unreadNotifications() { return record(await apiClient.get<unknown>("/notifications/unread-count")).unreadCount as number; }
export async function markNotificationRead(id:string) { return normalize(await apiClient.patch<unknown>("/notifications/"+encodeURIComponent(id)+"/read")); }
export async function markAllNotificationsRead() { return record(await apiClient.post<unknown>("/notifications/read-all")); }
export async function getNotificationPreferences() { const item=record(await apiClient.get<unknown>("/notification-preferences")); return { version:text(item.version,"Preference version is unavailable"), mandatoryCategories:array(item.mandatoryCategories).filter((value): value is string => typeof value==="string"), optionalCategories:booleanRecord(item.optionalCategories), channels:record(item.channels) as NotificationPreferences["channels"] }; }
export async function updateNotificationPreferences(optionalCategories:Record<string,boolean>) { const item=record(await apiClient.patch<unknown>("/notification-preferences",{body:{optionalCategories}})); return { version:text(item.version,"Preference version is unavailable"), mandatoryCategories:array(item.mandatoryCategories).filter((value): value is string => typeof value==="string"), optionalCategories:booleanRecord(item.optionalCategories), channels:record(item.channels) as NotificationPreferences["channels"] }; }
export function notificationDestination(item:CustomerNotification) { const routes:Record<NotificationResourceType,string>={repair:"/repair/track/",claim:"/account/warranty",return:"/account/returns",support_ticket:"/support",guidance:"/guidance",procurement_request:"/procurement",procurement_quotation:"/procurement",service_request:"/services",service_quotation:"/services",maintenance_plan:"/services"}; return item.resourceType==="repair" ? routes.repair+encodeURIComponent(item.resourceId) : routes[item.resourceType]; }
