import { apiClient } from "./client";
import type { ProductListResponse, PublicProduct, PublicVariant } from "./contracts";
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Unexpected API response"); return value as Record<string, unknown>; }
function text(value: unknown, fallback = ""): string { return typeof value === "string" ? value : fallback; }
function number(value: unknown, fallback = 0): number { return typeof value === "number" && Number.isFinite(value) ? value : fallback; }
function array(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }
function warranty(value: unknown): { version: string; terms: string } | undefined { if (!value || typeof value !== "object" || Array.isArray(value)) return undefined; const item = value as Record<string, unknown>; return typeof item.version === "string" && typeof item.terms === "string" ? { version: item.version, terms: item.terms } : undefined; }
function normalizeVariant(value: unknown): PublicVariant { const item = record(value); const availability = text(item.availability, "out_of_stock"); const condition = text(item.condition, "used_grade_b"); return { id: text(item.id ?? item._id), sku: text(item.sku), attributes: record(item.attributes ?? {}), price: number(item.price), availability: (["in_stock", "low_stock", "out_of_stock", "sourcing"] as string[]).includes(availability) ? availability as PublicVariant["availability"] : "out_of_stock", condition: (["new", "refurbished_grade_a", "refurbished_grade_b", "used_grade_a", "used_grade_b"] as string[]).includes(condition) ? condition as PublicVariant["condition"] : "used_grade_b", limitations: text(item.limitations) || undefined, warranty: warranty(item.warranty) }; }
export function normalizeProduct(value: unknown): PublicProduct { const item = record(value); const id = text(item.id ?? item._id); const slug = text(item.slug); if (!id || !slug) throw new Error("Product response is missing an identifier"); return { id, slug, name: text(item.name), description: text(item.description), category: text(item.category, "Uncategorised"), brand: text(item.brand, "Sanfaani"), images: array(item.images).filter((image): image is string => typeof image === "string"), tags: array(item.tags).filter((tag): tag is string => typeof tag === "string"), isFeatured: item.isFeatured === true, variants: array(item.variants).map(normalizeVariant) }; }
export async function fetchProducts(page = 1, limit = 12): Promise<ProductListResponse> { const data = await apiClient.get<{ products?: unknown[]; pagination?: unknown }>("/products?page=" + page + "&limit=" + limit); const pagination = record(data.pagination ?? {}); const products = array(data.products).map(normalizeProduct); return { products, pagination: { total: number(pagination.total, products.length), page: number(pagination.page, page), limit: number(pagination.limit, limit), pages: number(pagination.pages, 1) } }; }
export async function fetchProduct(slug: string): Promise<PublicProduct> { return normalizeProduct(await apiClient.get<unknown>("/products/" + encodeURIComponent(slug))); }
