"use client";
import Link from "next/link";
import { use, useCallback, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import Navbar from "@/components/Navbar";
import { EmptyState, LoadingState } from "@/components/ApiState";
import { fetchProduct } from "@/lib/api/productsApi";
import { addGadgetToCart } from "@/lib/functions/cartActions";
import type { PublicProduct, PublicVariant } from "@/lib/api/contracts";
import type { AppDispatch, RootState } from "@/lib/redux/store";
export default function ProductDetail({ params }: { params: Promise<{ id: string }> }) { const { id } = use(params); const dispatch = useDispatch<AppDispatch>(); const isAuthenticated = useSelector((state: RootState) => state.auth.isAuthenticated); const [product, setProduct] = useState<PublicProduct | null>(null); const [selected, setSelected] = useState<PublicVariant | null>(null); const [state, setState] = useState<"loading" | "ready" | "error" | "not_found">("loading"); const [message, setMessage] = useState<string | null>(null); const load = useCallback(async () => { try { const data = await fetchProduct(id); setProduct(data); setSelected(data.variants[0] ?? null); setState("ready"); } catch { setState("not_found"); } }, [id]); useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]); if (state === "loading") return <><Navbar /><main className="mx-auto max-w-5xl px-6 py-16"><LoadingState>Loading product details…</LoadingState></main></>; if (state === "not_found" || !product) return <><Navbar /><main className="mx-auto max-w-5xl px-6 py-16"><EmptyState title="This product is unavailable"><Link href="/shop" className="mt-4 inline-block font-semibold text-blue underline">Browse the catalogue</Link></EmptyState></main></>;  const available = selected?.availability === "in_stock" || selected?.availability === "low_stock";
  return <><Navbar /><main id="main-content" className="mx-auto max-w-5xl px-6 py-12"><Link href="/shop" className="text-sm font-semibold text-blue underline">Back to catalogue</Link><section className="mt-6 grid gap-10 rounded-3xl border border-navy-900/10 bg-white p-7 md:grid-cols-2"><div className="grid min-h-64 place-items-center rounded-2xl bg-paper text-lg text-mist">Product image available from catalogue</div><div><p className="text-xs font-semibold uppercase tracking-widest text-mist">{product.category}</p><h1 className="mt-2 font-display text-4xl font-semibold text-ink">{product.name}</h1><p className="mt-4 text-mist">{product.description}</p><fieldset className="mt-6"><legend className="font-semibold">Choose a condition</legend><div className="mt-2 flex flex-wrap gap-2">{product.variants.map((variant) => { const label = [variant.condition.replaceAll('_', ' '), ...Object.values(variant.attributes ?? {})].join(" - "); return <button type="button" key={variant.id} onClick={() => setSelected(variant)} aria-pressed={selected?.id === variant.id} className={'rounded-full border px-3 py-2 text-sm ' + (selected?.id === variant.id ? 'border-gold bg-gold/10' : 'border-navy-900/20')}>{label}</button>})}</div></fieldset><p className="mt-6 font-display text-3xl font-semibold">{selected ? '₦' + selected.price.toLocaleString('en-NG') : 'Variant unavailable'}</p><p className="mt-1 text-sm text-mist">Availability: {selected?.availability.replaceAll('_', ' ') ?? 'Unavailable'}</p>{message && <p role="status" className="mt-3 text-sm text-mist">{message}</p>}<button type="button" disabled={!selected || !available} onClick={() => selected && void addGadgetToCart({ product, variant: selected, isAuthenticated, dispatch }).then(() => setMessage("Added to your cart.")).catch(() => setMessage("We could not add that item. Please try again."))} className="mt-6 rounded-full bg-gold px-6 py-3 font-semibold text-navy-900 disabled:opacity-50">Add to cart</button></div></section></main></>;
}
