import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { guideBySlug, guides } from "@/content/guides";
import { siteUrl } from "@/lib/site";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const guide = guideBySlug((await params).slug); if (!guide) return { title: "Guide unavailable" }; const canonical = siteUrl ? "/guides/" + guide.slug : undefined; return { title: guide.title, description: guide.summary, alternates: canonical ? { canonical } : undefined, openGraph: { type: "article", title: guide.title, description: guide.summary, publishedTime: guide.publishedAt, modifiedTime: guide.updatedAt } }; }
export function generateStaticParams() { return guides.map((guide) => ({ slug: guide.slug })); }
export default async function BuyerGuidePage({ params }: Props) { const guide = guideBySlug((await params).slug); if (!guide) notFound(); const structuredData = JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: guide.title, description: guide.summary, datePublished: guide.publishedAt, dateModified: guide.updatedAt, author: guide.author ? { "@type": "Organization", name: guide.author } : undefined }).replace(/</g, "\u003c"); return <main id="main-content" className="mx-auto max-w-3xl px-6 py-12"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: structuredData }} /><Link href="/guides" className="text-sm font-semibold text-blue underline">All buyer guides</Link><article className="mt-6"><p className="text-xs font-semibold uppercase tracking-widest text-mist">Updated {guide.updatedAt}</p><h1 className="mt-3 font-display text-4xl font-semibold">{guide.title}</h1><p className="mt-4 text-lg text-mist">{guide.summary}</p><div className="mt-8 space-y-5 text-base leading-7 text-ink">{guide.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>{guide.author && <p className="mt-8 text-sm text-mist">Reviewed by {guide.author}</p>}<p className="mt-3 text-sm text-mist">Related categories: {guide.relatedCategories.join(", ")}</p></article></main>; }
