"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useSelector } from "react-redux";
import { EmptyState, ErrorState, LoadingState } from "./ApiState";
import { apiClient, errorMessage } from "@/lib/api/client";
import type { DashboardQueueItem } from "@/lib/api/contracts";
import type { RootState as ReduxState } from "@/lib/redux/store";
const PAGE_SIZE = 20;
function readQueue(payload: DashboardQueueItem[] | Record<string, DashboardQueueItem[]>) { return Array.isArray(payload) ? payload : Object.values(payload).flat(); }
export default function OperationsQueue() {
  const searchParams = useSearchParams(); const router = useRouter(); const pathname = usePathname(); const role = useSelector((state: ReduxState) => state.auth.user?.role); const [items, setItems] = useState<DashboardQueueItem[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [message, setMessage] = useState("The operations queue is unavailable.");
  const load = useCallback(async () => { try { const payload = await apiClient.get<DashboardQueueItem[] | Record<string, DashboardQueueItem[]>>("/dashboard/queue"); setItems(readQueue(payload)); setState("ready"); } catch (error) { setMessage(errorMessage(error, "The operations queue is unavailable.")); setState("error"); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const filter = searchParams.get("status") ?? ""; const query = searchParams.get("search")?.toLowerCase() ?? ""; const blocked = searchParams.get("blocked") === "true"; const page = Math.max(1, Number(searchParams.get("page")) || 1); const filtered = useMemo(() => items.filter((item) => (!filter || item.status === filter) && (!query || item.id.toLowerCase().includes(query) || item.type.toLowerCase().includes(query)) && (!blocked || item.blocked)), [blocked, filter, items, query]); const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  function update(values: Record<string, string | number | null>) { const params = new URLSearchParams(searchParams.toString()); Object.entries(values).forEach(([key, value]) => value === null || value === "" ? params.delete(key) : params.set(key, String(value))); router.push(pathname + (params.size ? "?" + params : "")); }
  return <main id="main-content" className="mx-auto max-w-7xl px-6 py-10"><h1 className="font-display text-3xl font-semibold text-ink">Operations queue</h1><p className="mt-2 text-sm text-mist">Role: {role?.replaceAll("_", " ")}. The queue contains only fields authorized by the API.</p><form className="mt-6 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); update({ search: String(data.get("search") ?? ""), status: String(data.get("status") ?? ""), blocked: data.get("blocked") === "on" ? "true" : null, page: 1 }); }}><label className="text-sm">Search<input name="search" defaultValue={searchParams.get("search") ?? ""} className="ml-2 rounded-lg border px-2 py-1" /></label><label className="text-sm">Status<input name="status" defaultValue={filter} className="ml-2 rounded-lg border px-2 py-1" /></label><label className="flex items-center gap-1 text-sm"><input name="blocked" type="checkbox" defaultChecked={blocked} />Blocked</label><button className="rounded-full bg-gold px-4 py-2 text-sm font-semibold text-navy-900">Apply</button></form><section className="mt-6">{state === "loading" ? <LoadingState>Loading your authorized queue…</LoadingState> : state === "error" ? <ErrorState message={message} onRetry={() => void load()} /> : visible.length === 0 ? <EmptyState title="No queue items match these filters" /> : <><div className="overflow-x-auto rounded-2xl border border-navy-900/10 bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b bg-paper text-mist"><th className="p-4">Item</th><th className="p-4">Status</th><th className="p-4">SLA</th><th className="p-4">Assignment</th><th className="p-4">Updated</th></tr></thead><tbody>{visible.map((item) => <tr key={item.type + item.id} className="border-b last:border-0"><td className="p-4 font-semibold">{item.type} · {item.id}</td><td className="p-4"><span className="rounded-full bg-paper px-2 py-1">{item.status}</span>{item.blocked && <span className="ml-2 text-amber-800">Blocked</span>}</td><td className="p-4">{item.slaState ?? "UNSPECIFIED"}</td><td className="p-4">{item.assignedTo ?? "Unassigned"}</td><td className="p-4">{new Date(item.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div><nav className="mt-5 flex justify-center gap-3" aria-label="Operations queue pages"><button type="button" disabled={page === 1} onClick={() => update({ page: page - 1 })} className="rounded-full border px-4 py-2 disabled:opacity-50">Previous</button><span className="py-2 text-sm">Page {page} of {pages}</span><button type="button" disabled={page >= pages} onClick={() => update({ page: page + 1 })} className="rounded-full border px-4 py-2 disabled:opacity-50">Next</button></nav></>}</section></main>;
}
