import Link from "next/link";
import Navbar from "@/components/Navbar";

export const metadata = { title: "Upgrades, setup and maintenance" };
const categories = [
  ["Device upgrade", "Hardware improvement requests need an assessment before compatibility or parts can be confirmed."],
  ["New-device setup", "A setup service is distinct from repair work and from software licensing."],
  ["Software setup", "Customer-owned licences and third-party requirements need explicit assessment."],
  ["Data migration", "Migration scope and backup responsibilities must be confirmed before work."],
  ["Preventive maintenance", "Maintenance is not a promise that a device is defect-free or covered by warranty."],
  ["Maintenance plan", "Coverage, renewal, visit limits, and cancellation must come from versioned server terms."],
];
export default function ServicesPage() { return <><Navbar /><main id="main-content" className="mx-auto max-w-4xl px-6 py-12"><h1 className="font-display text-3xl font-semibold">Services and maintenance</h1><p className="mt-3 max-w-3xl text-mist">Compatibility guidance is preliminary until a server-supported assessment or staff review is available. Never include passwords, recovery keys, payment credentials, or other secrets in a support message or attachment.</p><section className="mt-8 grid gap-4 sm:grid-cols-2">{categories.map(([title, description]) => <article key={title} className="rounded-2xl border border-navy-900/10 bg-white p-5"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-mist">{description}</p></article>)}</section><section className="mt-7 rounded-2xl border border-navy-900/10 bg-paper p-6"><h2 className="font-display text-xl font-semibold">Important responsibilities</h2><ul className="mt-3 space-y-2 text-sm text-mist"><li>Back up data before service; the current server contract does not record a separate service acknowledgement.</li><li>Bring proof of ownership for software licences where needed; licences are not included unless a future quote itemises them.</li><li>Do not send account credentials or recovery keys.</li><li>Assessment results, exclusions, customer responsibilities, payment/deposit requirements, and schedules must be returned by the service API before they can be presented as confirmed.</li></ul></section><section role="status" className="mt-6 rounded-2xl border border-navy-900/10 bg-white p-6"><h2 className="font-semibold">Service requests are unavailable</h2><p className="mt-2 text-sm text-mist">There is no backend customer contract for compatibility requests, service quotes/decisions, maintenance plans, service history, evidence association, or versioned responsibility disclosures. No request, quote approval, maintenance entitlement, or service history is simulated here.</p><Link href="/support" className="mt-4 inline-block font-semibold text-blue underline">Contact support about a service</Link></section></main></>;
}
